---
title: "deSolve Bibliography"
output: 
  html_document:
    theme: cosmo
bibliography: deSolve.bib
csl: plos.csl
---

<head><base target="_top" /></head>

The following bibliography may serve as a starting point for further reading. 
It can be downloaded as bibtex [.bib-file](deSolve.bib).

### Package documentation

* **Manuals:** @deSolve-Manual, @deSolve-introduction, @compiledCode

* **Papers:** @Soetaert2010-JSS-deSolve, @Soetaert2010-JSS-FME, @Soetaert2010-RJournal

* **Books:** @Soetaert2009-Book, @Soetaert2012-Book

* **Conferences:** @Soetaert-Rennes, @Petzoldt-Rennes, @Petzoldt-UCLA, @Petzoldt-Warwick,
@Soetaert-ICNAAM, @Soetaert-Tutorial-Warwick, @Soetaert2014, @Tutorial-UCLA, @Soetaert2010-AIP

* **Papers about related software:** @Setzer2001, @Mazzia2014-bvpSolve, @Soetaert2012, @Soetaert2010-ReacTran

* **Some books from other authors:** @Ellner2006,@Stevens2009


### References of the original algorithms

* **Runge-Kutta algorithms:** @Kutta1901, @Fehlberg1967, @Dormand1980, 
@Prince1981, @Butcher1987, @Bogacki1989, @Cash1990, @EngelnMuellges1996, @Press2007


* **ODEPACK algorithms:** @Hindmarsh1983, @Petzold1983, @Petzold1983a, @Brown1989,
@BrownHindmarsh1989, @Brown1994, @Brenan1996, @BrownHindmarshPetzold1998, @Hairer2009, @Hairer2010

Please consult the original publications for gaining full
understanding of the algorithms.

### Related software

* Related packages from the authors of deSolve: 
[rootSolve](http://cran.r-project.org/package=rootSolve), 
[bvpSolve](http://cran.r-project.org/package=bvpSolve), 
[FME](http://fme.r-forge.r-project.org/), 
[ReacTran](http://cran.r-project.org/package=ReacTran), 
[marelac](http://cran.r-project.org/package=marelac), 
[simecol](http://simecol.r-forge.r-project.org), 
[ccSolve](https://github.com/karlines/ccSolve), 
[rodeo](https://github.com/dkneis/rodeo)

* The [CRAN Task View **Differential Equations**](https://cran.r-project.org/web/views/DifferentialEquations.html)
gives an even more comprehensive listing, including related work of other authors. 


### Papers citing deSolve

* Ask
  [Google Scholar](https://scholar.google.de/scholar?cites=7659476596233292461)
  who is citing our JSS paper


## Bibliography




